# Generated by Django 4.1.2 on 2023-03-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=80)),
                ('adress', models.CharField(max_length=80)),
                ('cargo_info', models.CharField(max_length=100)),
                ('eta', models.IntegerField(max_length=20)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
