# Generated by Django 4.1.2 on 2023-03-10 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_orders_eta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='adress',
            new_name='address',
        ),
    ]
