# Generated by Django 4.1.2 on 2023-03-10 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_rename_adress_orders_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
