# Generated by Django 4.1.7 on 2023-03-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trailers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trailer_make', models.CharField(max_length=30)),
                ('trailer_model', models.CharField(max_length=30)),
                ('year', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=20)),
                ('trailer_image', models.ImageField(blank=True, null=True, upload_to='trailer-images/')),
                ('status', models.BooleanField(default=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trucks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_make', models.CharField(max_length=30)),
                ('truck_model', models.CharField(max_length=30)),
                ('year', models.PositiveIntegerField()),
                ('mileage', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=20)),
                ('truck_image', models.ImageField(blank=True, null=True, upload_to='truck-images/')),
                ('status', models.BooleanField(default=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
