# Generated by Django 4.1.7 on 2023-03-16 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trailers',
            name='trailer_image',
        ),
        migrations.RemoveField(
            model_name='trucks',
            name='truck_image',
        ),
    ]
