# Generated by Django 4.1.7 on 2023-03-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_remove_trailers_trailer_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailers',
            name='trailer_image',
            field=models.ImageField(blank=True, null=True, upload_to='trailer-images/'),
        ),
        migrations.AddField(
            model_name='trucks',
            name='truck_image',
            field=models.ImageField(blank=True, null=True, upload_to='truck-images/'),
        ),
    ]
