# Generated by Django 4.1.2 on 2023-03-17 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_trailers_trailer_image_trucks_truck_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailers',
            name='trailer_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/trailer-images/'),
        ),
        migrations.AlterField(
            model_name='trucks',
            name='truck_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/truck-images/'),
        ),
    ]
