# Generated by Django 4.1.2 on 2023-03-17 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_alter_trailers_trailer_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trailers',
            name='created',
        ),
        migrations.RemoveField(
            model_name='trailers',
            name='trailer_image',
        ),
        migrations.RemoveField(
            model_name='trailers',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='trucks',
            name='created',
        ),
        migrations.RemoveField(
            model_name='trucks',
            name='truck_image',
        ),
        migrations.RemoveField(
            model_name='trucks',
            name='updated',
        ),
    ]
