# Generated by Django 4.1.2 on 2023-03-17 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0005_remove_trailers_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trailers',
            old_name='color',
            new_name='colors',
        ),
        migrations.RenameField(
            model_name='trailers',
            old_name='trailer_make',
            new_name='trailer_makes',
        ),
        migrations.RenameField(
            model_name='trailers',
            old_name='trailer_model',
            new_name='trailer_models',
        ),
        migrations.RenameField(
            model_name='trailers',
            old_name='year',
            new_name='years',
        ),
        migrations.RenameField(
            model_name='trucks',
            old_name='color',
            new_name='colors',
        ),
        migrations.RenameField(
            model_name='trucks',
            old_name='mileage',
            new_name='mileages',
        ),
        migrations.RenameField(
            model_name='trucks',
            old_name='truck_make',
            new_name='truck_makes',
        ),
        migrations.RenameField(
            model_name='trucks',
            old_name='truck_model',
            new_name='truck_models',
        ),
        migrations.RenameField(
            model_name='trucks',
            old_name='year',
            new_name='years',
        ),
    ]
