# Generated by Django 4.1.2 on 2023-03-17 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0006_rename_color_trailers_colors_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trailers',
            old_name='colors',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='trailers',
            old_name='trailer_makes',
            new_name='trailer_make',
        ),
        migrations.RenameField(
            model_name='trailers',
            old_name='trailer_models',
            new_name='trailer_model',
        ),
        migrations.RenameField(
            model_name='trailers',
            old_name='years',
            new_name='year',
        ),
        migrations.RenameField(
            model_name='trucks',
            old_name='colors',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='trucks',
            old_name='mileages',
            new_name='mileage',
        ),
        migrations.RenameField(
            model_name='trucks',
            old_name='truck_makes',
            new_name='truck_make',
        ),
        migrations.RenameField(
            model_name='trucks',
            old_name='truck_models',
            new_name='truck_model',
        ),
        migrations.RenameField(
            model_name='trucks',
            old_name='years',
            new_name='year',
        ),
    ]
