# Generated by Django 4.1.2 on 2023-03-17 10:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0007_rename_colors_trailers_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailers',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trailers',
            name='trailer_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/trailer-images/'),
        ),
        migrations.AddField(
            model_name='trailers',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='trucks',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trucks',
            name='truck_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/truck-images/'),
        ),
        migrations.AddField(
            model_name='trucks',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
