# Generated by Django 4.1.7 on 2023-03-30 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('employee', 'employee'), ('manager', 'manager')], default='manager', max_length=100),
        ),
    ]
