# Generated by Django 4.1.2 on 2023-03-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='eta',
            field=models.DateField(),
        ),
    ]
