# Generated by Django 4.1.7 on 2023-03-25 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailers',
            name='registration_plate',
            field=models.CharField(default=10, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trucks',
            name='registration_plate',
            field=models.CharField(default=10, max_length=30),
            preserve_default=False,
        ),
    ]
